apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    haproxy.router.openshift.io/hsts_header: max-age=31536000;includeSubDomains;preload
spec:
  to:
    kind: Service
    name: {{ include "app.fullname" . }}
  tls:
    termination: "edge"
