apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
spec:
  selector:
    {{- include "app.selectorLabels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
