apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
    name: openshift-pipelines-operator-rh
    namespace: openshift-operators
  spec:
    channel: latest
    installPlanApproval: Automatic
    name: openshift-pipelines-operator-rh
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: openshift-pipelines-operator-rh.v1.10.3
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/openshift-gitops-operator.openshift-operators: ""
    name: openshift-gitops-operator
    namespace: openshift-operators
  spec:
    channel: latest
    installPlanApproval: Automatic
    name: openshift-gitops-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: openshift-gitops-operator.v1.8.3
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    labels:
      operators.coreos.com/devspaces.openshift-operators: ""
    name: devspaces
    namespace: openshift-operators
  spec:
    channel: stable
    installPlanApproval: Automatic
    name: devspaces
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: devspacesoperator.v3.6.0-0.1685322634.p