apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-demo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: devspaces-demo
    server: https://kubernetes.default.svc
  source:
    path: deployment/helm
    repoURL: https://github.com/gmodzelewski/devspaces-demo
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
